# ==== Obsidian ====
### Obsidian 当前仓库
GET http://127.0.0.1:6528/obsidian/current-vault

### Obsidian 当前笔记：打开的笔记
GET http://127.0.0.1:6528/obsidian/current-note


# === Dataview ===

### Dataview 查询主页信息
GET http://127.0.0.1:6528/dataview/page/主页

### Dataview 执行代码
POST http://127.0.0.1:6528/dataview/query
Content-Type: application/json

{
    "source": "LIST\nWHERE file.mtime >= date(now) - dur(1 day)\nSORT file.mtime desc"
}


# ==== 日记 ====

### 创建今日日记
GET http://127.0.0.1:6528/diary/create-today

### 读取今日日记
GET http://127.0.0.1:6528/diary/read-today

### 读取某天日记（日期格式：YYYYMMDD）
GET http://127.0.0.1:6528/diary/read/20250324

### 列出某月中的日记（日期格式：YYYYMM）
GET http://127.0.0.1:6528/diary/list-month/202503
