GET http://localhost:8010


### Obsidian 当前笔记：打开的笔记
GET http://localhost:8010/obsidian/current-note


# === Dataview ===

### Dataview 查询主页信息
GET http://localhost:8010/dataview/page/主页

### Dataview 执行代码
POST http://localhost:8010/dataview/query
Content-Type: application/json

{
    "source": "LIST\nWHERE file.mtime >= date(now) - dur(1 day)\nSORT file.mtime desc"
}


# ==== 日记 ====

### 创建今日日记
GET http://localhost:8010/diary/create-today

### 读取今日日记
GET http://localhost:8010/diary/read-today
