### 打印笔记中所有任务切换后字符串
POST http://127.0.0.1:6528/tasks/toggle-tasks
Content-Type: application/json

{
    "notepath": "_100-数字花园/收集/Python基础语法.md"
}


### 返回所有任务
POST http://127.0.0.1:6528/tasks/get-all-tasks
Content-Type: application/json

{
    "notepath": "_100-数字花园/收集/Python基础语法.md"
}


### 切换单个任务（效果等于左键复选框）
POST http://127.0.0.1:6528/tasks/toggle-task
Content-Type: application/json

{
    "line": 7,
    "status": "x",
    "text": "打印 Hello World",
    "notepath": "_100-数字花园/收集/Python基础语法.md"
}
