### 打印笔记中所有任务切换后字符串
POST http://localhost:6528/tasks/toggle-tasks
Content-Type: application/json

{
    "notepath": "_100-数字花园/收集/Python基础语法.md"
}


### 返回所有任务
POST http://localhost:6528/tasks/get-all-tasks
Content-Type: application/json

{
    "notepath": "_100-数字花园/收集/Python基础语法.md"
}
