# ==== 统计信息 ====

### 笔记总数
GET http://127.0.0.1:6528/stats/note-number


### 热力图（热点）
GET http://127.0.0.1:6528/stats/heatmap/1


### 仓库使用天数
GET http://127.0.0.1:6528/stats/use-days


### 最近编辑的十篇笔记
GET http://127.0.0.1:6528/stats/recent-edit
